# Generated by Django 5.0.3 on 2024-03-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('pb', 'Punjab'), ('mp', 'Madhaya Pradesh'), ('gj', 'Gujarat'), ('mh', 'Maharastra')], max_length=100),
        ),
    ]
