# Generated by Django 5.0.3 on 2024-03-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('mh', 'Maharastra'), ('pb', 'Punjab'), ('gj', 'Gujarat'), ('mp', 'Madhaya Pradesh')], max_length=100),
        ),
    ]
